### ISSUE TITLE
A product can have more than one category

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#104]
Now our users make a product for **T-Shirt** in category **Man** and another one **T-Shirt** in category **Woman**. They are not related, linked or comparable.
To me it would make sense, if you create a product **T-Shirt** and make that product available in some of the categories (For example in Man, Woman, Boy and Girl).
In this way, it's possible to gather information about all T-Shirts, all Shoes, etc.

@HaGuesto do you think this is important from a users point of view? We should discuss how this affects our development, but ofcourse after MVP.

**Comment by HaGuesto** [comment]
Database wise it makes it more complicated because you create a n-to-n relationship between product and category, but it is manageable and is useful later. 

I'm also not sure yet if the categories man,  women.... makes sense. We are mixing quite a lot of things there. 

At the end we should decide to make it as easy as possible to select a product. This UI should be easy and understandable
