### ISSUE TITLE
A box should be deletable

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#177]
In the future boxes will be ordered by other groups or they will move in lots of ways, but besides that, it should be possible to just delete it (at least until more advanced tracking or changing options are available)

**Comment by bfirsh** [comment]
It should use an `isDeleted` flag, like products. We also need a data migration to set `isDeleted` to `false` on all existing products, because Firestore can't check null/undefined in a query (!).

To someone from the Tripadvisor hack day reading this - sadly this is not an easy change because we don't have a framework for doing migrations yet. Feel free to tackle this without a migration though, and we can always add that later.

**Comment by HaGuesto** [comment]
Closed ("Paused") due to discussion #275.
