### ISSUE TITLE
Should we use Redux?

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise#192]
### Questions for tripAdvisor HackDay
Shoul we use Redux or drop it? Why? Is there any alternative you can think of?

**Comment by spielhoelle** [comment]
What about using [Context](https://reactjs.org/docs/context.html) ?

**Comment by rubenspgcavalcante** [comment]
Before using context we need be very organised and concise.
As I've put on the slack discussion:

> Hi. Well, you can have multiple stores around your app as you can create as much contexts (providers/consumers) as you want.
> The problem is, if you already uses redux it can be confusing being using both of the alternatives.
> The other use case for us is something that I really enjoy on it: the fact that the consumer is a render props, is much more explicit than doing stuff using Hight Order Components.
> When you start nest your own HOCs and lib HOCs you start to be confused on which some props comes from. Can be own props, can be from a HOC, can be from a lib (and the caos is done :fire: )
> 
> So, my opinion (and I’m totally open to hear yours too :slightly_smiling_face: ) is whenever we need to create a custom HOC for boxwise, instead create it as a context

So, we can have a unique context providing something similar to redux or multiple ones, something similar to [MobX](https://github.com/mobxjs/mobx).
But the main point is, we're going to be changing to some custom architecture that would make things harder to developers who wants to help out with the project. I mean, if we're able to make a design to separate the business logic (actions/thunks) from the views (components) and connect both together in a simpler way than redux, I'm totally in :)

**Idea:** One solution is turn the firebase collection queries into providers, and whoever wants that information, can fetch by simply wrapping the consumer into the component. When the internal collection is updated, so is the components which uses the consumers, dealing with the problem of one source of truth. Still using this conception, but for each context/collection of data (again similar to MobX).
This way we can centralise all impure/async api calls into contexts. The problem is to turn this generic for every action that's not a API call.

**Comment by rubenspgcavalcante** [comment]
And for the problem of the contributors without any exp. in Redux, is something that probably all of us faced in our life as developers:
- When there's no docs, the **code** is the best documentation.

Redux forces you to **always** follow that same workflow:
- create the component
- create the state within the store for that feature
- create the actions so you can modify this state
- create a container to bind both actions and the state itself to your component
- take a cup of coffee ☕️ 

The separations of concerns is also pretty clear, and as the developer knows the data should not go directly on the component, but the state, it will force to create the business rules within the actions.
Of course, if we have a good docs/styleguide to make the things clear, it's awesome, but taking for me, I always try to base myself in other working features while contributing to any open source project.

**Comment by HaGuesto** [comment]
I will close this issue since we decided to use Redux. We will work on a style guide to explain how to use Redux (#274).
