### ISSUE TITLE
Formik or no Formik?

### ISSUE THREAD

**Issue by HaGuesto** [boxwise/boxwise#276]
Formik was an easy and fast handler to create our first forms in Boxwise. However, the first problems came up in the development of new features:
- We are using a binding between Formik and Material-UI which only binds the Material-UI `TextField` to Formik. Material-UI `TextField` in turn does not support itself Autocompletion in a Select-Field, but suggests `react-select`. It is quite complicated to combine these three packages. (c.f. #93 or  branch `93/search_to_select_product`). --> In general, we are in some way slowing us down for more complicated forms with Formik.
- Formik is a bit unclear for howto set the `InitialValue`. In #263 and #264 we had to do a little hack for the initialValue to Select a category for new products. (@rubenspgcavalcante am I right? Feel free to change this)
- In general, there have been complaints that contributors have never used Formik and that the doc is not the best.

### Possible next steps:
- We keep Formik as our main form handler.
- We drop Formik completely and refactor to our own forms.
- We keep Formik and write our own forms when Formik is too complicated to use.

Tell us your opinion!

**Comment by rubenspgcavalcante** [comment]
For me we can simply go just by material-ui. I mean, the benefit of formik: the form validations are something easy to implement as the app forms right now are't ultra complex ones.
While working with Formik I've struggled because it doesn't is so declarative and sometimes magical values are incoming from upper components, making even harder to understand simple flows within the app. Also @HaGuesto tried to detach some component (to turn it more reusable) from within the form and had hard times as it was binded to these magical values.
As any Redux app, validations can just go within the actions (business rules) and if something is wrong we can just put the error on the store **or** make the action throw an error forcing the component to deal with it within the ```promise.catch``` of this action. Other solutions as doing inside the internal component state are also fully accepted :)

**Comment by HaGuesto** [comment]
In our last talk we decided that we will drop Formik for simplicity and we will write our own forms in the future. How this should look like will be explained in #274.
