### ISSUE TITLE
Could we make better use of subcollections?

### ISSUE THREAD

**Issue by bfirsh** [boxwise/boxwise#73]
We have a lot of things which are siloed within organizations: products, boxes, etc. Perhaps this would be better structured as subcollections.

Advantages of doing it this way:
- A bit neater
- Would mean we don't need to create composite indexes for everything

Disadvantages:
- Might make it harder to do some things in the future when organizations aren't siloed. E.g. listing all available boxes across all warehouses.

**Comment by HaGuesto** [comment]
I'm asking myself this question quite often. Maybe we are still too caught up in the SQL world.
The problem is that you cannot query over the parents of subcollections.
Therefore, Ifeel that in general the moment you have a UI for something it should be a root collection and vice versa. 

The only example where I would use subcollections right now is to track the histroy of a box.

**Comment by HaGuesto** [comment]
### Questions for tripAdvisor HackDay
Google Firestore is a NoSQL database divided in documents and collections. Until now we only have root collections. Should we make better use of subcollections?
