### ISSUE TITLE
Implement UX changes

### ISSUE THREAD

**Issue by barto74** [boxwise/boxwise#89]
In a new UX sketch we sketched how lists, forms, interface elements, colours and fonts are used.
As much as possible we should style the components according to this sketch in theme.js, to make it easier to quickly create new screens.

The blue color (#009BD9) and the font are part of the Drop App visual identity

- [ ] The visual category/product selection needs some design elaboration. All places where a category/product has to be selected, it should work this way, so this needs to become a component
- [ ] Modals should be the same throughout the app - full screen on mobile, on bigger screens it should be smaller, not filling the screen.
- [ ] Always a blue header for a normal screen and a grey header for a modal

Interactive walkthrough [here](https://xd.adobe.com/view/5b5416a4-680c-40dd-6351-20f6a85c8323-2d65/)
<img width="1102" alt="screen shot 2018-06-08 at 14 38 09" src="https://user-images.githubusercontent.com/38283578/41158572-b725a0ea-6b29-11e8-99ba-50c40f998f64.png">

**Comment by HaGuesto** [comment]
@barto74 Could this be a Design task for the Hackathon?

**Comment by barto74** [comment]
@HaGuesto it is not so much design work as well as implementation of the design in material ui and some custom css.

**Comment by HaGuesto** [comment]
Would you like to write it down as a good first issue for the Hackathon or should I do it?

**Comment by HaGuesto** [comment]
@barto74 
- I like the animations of the products, but how would you like to do that if the user can manage their own products? Do you want to create a bunch of animations and the coordinators should decide which animation should be used for which product?
It seems a like a lot of work to create all the animations (don't forget food and Hygiene!). Maybe the second step could only be text?
- We could also make the Dialog Box bigger and offer a search box or the 5 most used products (or both beneath the squares. Does that make sense (UI-wise) or is it too complicated?
- Due to the ambiguity of the current categories (Adult and Man) should we maybe change the categories? #159

**Comment by barto74** [comment]
@HaGuesto you probably mean to say icons instead of animations? 
And yes, i want to generate a bunch of icons, for clothes, food, hygiene. I think especially in the second step we need icons, it is a proven way to have people select faster and with less errors.
As an addition to this, we might add search options or most used products, but i think we should do that later if user feedback or user analysis demand it.
So this is why I made #54, that is actually that library of icons.

And for the categories: that refers to other discussions, regarding if we actually want the category list to be user editable or not, if we want to re-assess the desired categories if its not editable. My idea: we should keep it user editable, so they have the freedom to arrange to their wishes. The same library should be available to choose an icon for each category. 

And next to that: we can also give an option to select a color for a category, when editing categories. That makes selection of categories and products even faster and in the warehouse people could add that color to the label with a sticker (this is one of the recommendations from the breda students group).
